apiVersion: apps/v1
kind: Deployment
metadata:
  name: board
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: board
          ports:
            - containerPort: 8080
