apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: abcdefg
- name: user # 이 부분을 새로 추가합니다.
  newName: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/donkey-app
  newTag: "latest" # 또는 동적으로 설정된 태그
resources:
- ../../base
patches:
- path: front-deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: demo-frontend
    namespace: default
- path: front-service-patch.yaml
  target:
    group: ""
    version: v1
    kind: Service
    name: demo-frontend
    namespace: default
# 여기에 user 서비스에 대한 새로운 패치 파일을 추가합니다.
- path: user-deployment-patch.yaml # user 디플로이먼트에 대한 패치 파일
  target:
    group: apps
    version: v1
    kind: Deployment
    name: user
    namespace: default
- path: user-service-patch.yaml # user 서비스에 대한 패치 파일
  target:
    group: ""
    version: v1
    kind: Service
    name: user-service
    namespace: default
