apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: demo-frontend
  newName: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: abcdefg
- name: demo-testrepo/my-spring-app
  newName: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/demo-testrepo/my-spring-app
  newTag: latest
- name: donkey-app
  newName: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/donkey-app
  newTag: f91addf3ee3ef32ad21faf9c82f0747fb7dbe5cc
- name: user
  newName: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/donkey-app
  newTag: latest

resources:
- ../../base

patches:
- path: front-deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: demo-frontend
    namespace: default
    version: v1
- path: front-service-patch.yaml
  target:
    kind: Service
    name: demo-frontend
    namespace: default
    version: v1
- path: user-deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: user
    namespace: default
    version: v1
- path: user-service-patch.yaml
  target:
    kind: Service
    name: user-service
    namespace: default
    version: v1
- path: board-deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: board-deploymnet
    namespace: default
    version: v1
- path: board-service-patch.yaml
  target:
    kind: Service
    name: board-service
    namespace: default
    version: v1
