apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: abcdefg
resources:
- ../../base
patches:
- path: front-deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: demo-frontend
    namespace: default
- path: front-service-patch.yaml
  target:
    group: ""
    version: v1
    kind: Service
    name: demo-frontend
    namespace: default
