apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: demo-frontend # 이미 기존에 있던 이미지 설정
  newName: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: abcdefg
- name: user # 새롭게 추가된 user 이미지 설정
  newName: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/donkey-app
  newTag: "latest" # 이 태그는 동적으로 설정된 태그나 커밋 SHA로 대체해야 할 수 있습니다.

resources:
- ../../base

patches:
- path: front-deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: demo-frontend
    namespace: default
    version: v1
- path: front-service-patch.yaml
  target:
    kind: Service
    name: demo-frontend
    namespace: default
    version: v1
- path: user-deployment-patch.yaml # user 디플로이먼트에 대한 패치 파일
  target:
    group: apps
    version: v1
    kind: Deployment
    name: user
    namespace: default
- path: user-service-patch.yaml # user 서비스에 대한 패치 파일
  target:
    group: ""
    version: v1
    kind: Service
    name: user-service
    namespace: default
