apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend-deployment.yaml
  - frontend-service.yaml
  - module1-deployment.yaml
  - module1-service.yaml
  - module2-deployment.yaml
  - module2-service.yaml
  - board-deploy.yaml
  - board-service.yaml
  - user-deployment.yaml
  - user-service.yaml
