apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: 227250033304.dkr.ecr.ap-northeast-2.amazonaws.com/donkey-user:f91addf3ee3ef32ad21faf9c82f0747fb7dbe5cc
          ports:
            - containerPort: 8080
